# Generated by Django 5.0.3 on 2024-04-06 09:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordcollection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artist',
            name='unique_artist_name',
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_artist_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(models.F('name'), name='unique_artist_name'),
        ),
    ]
