# Generated by Django 5.0.3 on 2024-04-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordcollection', '0002_remove_artist_unique_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
