# Generated by Django 5.0.3 on 2024-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordcollection', '0003_alter_track_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
