# Generated by Django 5.0.3 on 2024-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordcollection', '0005_alter_artist_name_alter_track_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.SmallIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='albumartist',
            name='position',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trackartist',
            name='position',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
