# Generated by Django 5.0.4 on 2024-04-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordcollection', '0006_alter_album_title_alter_album_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
